# Generated by Django 5.0 on 2024-01-04 23:52

from django.db import migrations, models

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    groups = ['Field', 'Phone', 'Internal Manager', 'External Manager']

    for group_name in groups:
        Group.objects.get_or_create(name=group_name)

class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(create_groups),
    ]
