# Generated by Django 5.0.6 on 2024-06-08 22:39

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_customuser_avatar'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
            ],
            options={
                'permissions': (('show_on_admin_dashboard', 'Show on Admin Dashboard'),),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('show_on_admin_dashboard', 'Show on Admin Dashboard'),)},
        ),
    ]
