# Generated by Django 5.0.6 on 2024-05-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='disposition_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
