# Generated by Django 5.0.6 on 2024-05-28 20:10

import Appointments.models
import django.db.models.deletion
from django.db import migrations, models

def add_dispositions(apps, schema_editor):
    Disposition = apps.get_model('Appointments', 'Disposition')
    dispositions = [
        "Disposition Needed",
        "Sold",
        "Consultant Reschedule",
        "Customer No Show",
        "Not Interested at Door",
        "Not Interested After Presentation",
        "Customer Requested a Phone Reschedule",
        "Cancelled Prior to Visit",
    ]
    for disposition_name in dispositions:
        Disposition.objects.get_or_create(name=disposition_name)

class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0003_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='disposition_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='disposition',
            field=models.ForeignKey(blank=True, default=Appointments.models.Appointment.get_default_disposition, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appointments.disposition'),
        ),
        migrations.RunPython(add_dispositions),
    ]
