# Generated by Django 5.0.6 on 2024-05-28 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0004_disposition_remove_appointment_disposition_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'permissions': (('change_all_appointment_details', 'Can change all appointment details'),)},
        ),
    ]
