# Generated by Django 5.0.6 on 2024-05-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0005_alter_appointment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='recording',
            field=models.TextField(blank=True, default=''),
        ),
    ]
