# Generated by Django 5.0.6 on 2024-06-08 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0007_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disposition',
            options={'permissions': (('show_on_admin_dashboard', 'Show on Admin Dashboard'),)},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'permissions': (('show_on_admin_dashboard', 'Show on Admin Dashboard'),)},
        ),
    ]
