# Generated by Django 5.0.6 on 2024-06-12 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone

def set_placeholder_contract(apps, schema_editor):
    Contract = apps.get_model('Appointments', 'Contract')
    Appointment = apps.get_model('Appointments', 'Appointment')
    
    placeholder_contract = Contract.objects.get_or_create(
        name='Placeholder Contract',
        receivable=0.00,
        payable=0.00,
        bonus_eligible=False,
        start_date=timezone.now(),
        end_date=timezone.now() + timezone.timedelta(days=3650)
    )[0]
    
    Appointment.objects.filter(contract__isnull=True).update(contract=placeholder_contract)

class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0008_alter_disposition_options_alter_note_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('receivable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_eligible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('users', models.ManyToManyField(limit_choices_to={'groups__name': 'field'}, related_name='contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('show_on_admin_dashboard', 'Show on Admin Dashboard'),),
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appointments.contract'),
        ),
        migrations.RunPython(set_placeholder_contract),
    ]
