# Generated by Django 5.0.6 on 2024-06-16 00:48

import Appointments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0009_contract_appointment_contract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='users',
            field=models.ManyToManyField(limit_choices_to=Appointments.models.Contract.limit_field_agent_choices, related_name='contracts', to=settings.AUTH_USER_MODEL),
        ),
    ]
