# Generated by Django 5.0.6 on 2024-06-19 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Availability', '0002_alter_timeslot_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='is_available',
        ),
    ]
