# Generated by Django 5.0.6 on 2024-06-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Availability', '0006_territory_created_at_territory_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='territory',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
