# Generated by Django 5.0.6 on 2024-06-26 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Availability', '0007_territory_is_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='territory',
            options={'ordering': ['user', 'name'], 'permissions': (('show_on_admin_dashboard', 'Show on Admin Dashboard'),), 'verbose_name': 'Territory', 'verbose_name_plural': 'Territories'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['user', 'date', 'hour'], 'permissions': (('show_on_admin_dashboard', 'Show on Admin Dashboard'),), 'verbose_name': 'TimeSlot', 'verbose_name_plural': 'TimeSlots'},
        ),
    ]
