# Generated by Django 5.0.6 on 2024-06-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Availability', '0008_alter_territory_options_alter_timeslot_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='is_weekly_default',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='hour',
            field=models.IntegerField(choices=[(7, '7:00'), (8, '8:00'), (9, '9:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00')]),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='source',
            field=models.CharField(choices=[('user', 'User'), ('pending', 'Pending'), ('recurring', 'Recurring'), ('settings', 'Settings')], default='user', max_length=10),
        ),
    ]
