# Generated by Django 5.0.6 on 2024-07-03 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Availability', '0009_remove_timeslot_is_weekly_default_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('territory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dates', to='Availability.territory')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='unavailable', max_length=255)),
                ('start_time', models.TimeField()),
                ('source', models.CharField(choices=[('user', 'User'), ('pending', 'Pending'), ('recurring', 'Recurring'), ('settings', 'Settings')], default='user', max_length=10)),
                ('invitees_allowed', models.IntegerField(default=1)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='Availability.date')),
            ],
        ),
    ]
