# Generated by Django 4.2.7 on 2023-11-14 21:56

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_alter_customuser_email_first_name_and_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+12223334444', max_length=128, region='US', unique=True),
            preserve_default=False,
        ),
    ]
