# Generated by Django 5.0.6 on 2024-06-08 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': (('change_customer_details_on_appointment_form', 'Can change customer details on appointment form'), ('show_on_admin_dashboard', 'Show on Admin Dashboard'))},
        ),
    ]
